#!/usr/bin/env bash
# ╔════════════════════════════════════════════════════╗
# │ Print_Banner - UI de instalación                   │
# │ Versión: 2.0                                       │
# │ Autor: Daniel Calderon - Kapelu                    │
# │ Fecha: 19-02-2026                                  │
# │ WebSite: https://danielcalderon.vercel.app/        │
# │ Github: https://github.com/Kapelu                  │
# ╚════════════════════════════════════════════════════╝
set -Eeuo pipefail
IFS=$'\n\t'
clear

print_banner() {
  local msg="$1"
  echo -e "${COLOR[green]}════════════════════════════════════════════════════${COLOR[reset]}"
  echo -e "$msg"
  echo -e "${COLOR[green]}════════════════════════════════════════════════════${COLOR[reset]}"
  echo -e ""
}
sleep 3