#!/usr/bin/env bash
# ╔════════════════════════════════════════════════════╗
# │ Logging Helper para kpsetup de Ubuntu              │
# │ Versión: 4.0                                       │
# │ Autor: Daniel Calderon - Kapelu                    │
# │ Fecha: 19-02-2026                                  │
# │ WebSite: https://danielcalderon.vercel.app/        │
# │ Github: https://github.com/Kapelu                  │
# ╚════════════════════════════════════════════════════╝
logo() {
  printf "%b\n" "${COLOR[green]}"
  cat << "EOF"
██   ██  ██████   ███████  ███████  ████████  ██    ██  ██████
██  ██   ██   ██  ██       ██          ██     ██    ██  ██   ██
█████    ██████   ███████  █████       ██     ██    ██  ██████
██  ██   ██            ██  ██          ██      ██  ██   ██
██   ██  ██       ███████  ███████     ██       ████    ██
EOF
  printf "%b\n" "${COLOR[reset]}"
}
